# Generated by Django 5.0.3 on 2024-04-02 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_usuarios', '0003_alter_usuario_cep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='sobrenome',
        ),
    ]
